services:
  takoyaki:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      DATA_SYNC_INTERVAL_SECONDS: "${DATA_SYNC_INTERVAL_SECONDS:-10}"
      PUBLIC_HOST: "${PUBLIC_HOST:-}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
